version: "3.1"

services:
  db:
    container_name: postgres-clines
    image: postgres:15.3
    #restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "${DB_PORT:-127.0.0.1:5432}:5432"

  adminer:
    image: adminer
    #restart: always
    ports:
      - 8088:8080
